services:
  - type: web
    name: cv-parser-pro
    env: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/cv_parser_pro
      sizeGB: 1
