services:
  - type: web
    name: cv-parser-pro
    env: node
    plan: free
    buildCommand: npm ci --only=production && npm rebuild better-sqlite3 --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1
